DECLARE
    V_EMP_NAME HR.EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
    SELECT
        FIRST_NAME
    INTO V_EMP_NAME
    FROM
        HR.EMPLOYEES
    WHERE
        ROWNUM = 1;

    DBMS_OUTPUT.PUT_LINE('USING %TYPE - Employee Name : ' || V_EMP_NAME);
END;
/